name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      # Install dependencies
      - name: Install dependencies
        run: uv sync --frozen --all-extras


      # no lint

      # Type check with pyright
      - name: Type check with pyright
        run: uv run pyright
